version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8086:8086
    depends_on:
      - mysql_db
    links:
      - mysql_db:cedsif
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cedsif
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root